services:
  # https://github.com/hashicorp/terraform-mcp-server
  terraform-mcp-server:
    container_name: terraform-mcp-server
    restart: unless-stopped
    image: hashicorp/terraform-mcp-server:${TF_MCP_VERSION}
    ports:
      - "8081:8080"
    environment:
      - TRANSPORT_HOST=0.0.0.0
      - TRANSPORT_PORT=8080
      - TRANSPORT_MODE=streamable-http
      - TFE_ADDRESS=${TFE_ADDRESS}
      - TFE_TOKEN=${TFE_TOKEN}
  
  # https://github.com/hashicorp/vault-mcp-server
  vault-mcp-server:
    container_name: vault-mcp-server
    restart: unless-stopped
    image: hashicorp/vault-mcp-server:${VAULT_MCP_VERSION}
    ports:
      - "8082:8080"
    environment:
      - TRANSPORT_HOST=0.0.0.0
      - TRANSPORT_PORT=8080
      - TRANSPORT_MODE=streamable-http
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_NAMESPACE=${VAULT_NAMESPACE}
